version: '3'

services:
  ml-ui:
    image: marwane8/ml-ui
    ports:
      - "3000:3000"
    depends_on:
      - ml-api

  ml-api:
    image: marwane8/ml-api
    ports:
      - "8000:80"
    environment:
      - JWT_SECRET_KEY=${JWT_KEY1}
      - JWT_REFRESH_SECRET_KEY=${JWT_KEY2}
      - DB_URL=./database/muslim-league.db
    volumes:
      - ./ml-api/database:/code/database


